# state.py
from typing import Annotated, NotRequired, Literal
from typing_extensions import TypedDict
from langchain_core.messages import AnyMessage
import operator
from pydantic import BaseModel, Field
from typing import Optional


# Pudantic models

class Retrieval(BaseModel):
    title : str
    summary: str
    source_url: str
    authors: list[str]
    categories: list[str] 
    pdf_url: str
    short_id: str

class ListRetrievals(BaseModel):
    retrievals: list[Retrieval]

class PICOC(BaseModel):
    """The Kitchenham bounding box for the study's scope."""
    population: str = Field(description="The target group, domain, or artifacts studied (e.g., Senior Developers, Open-source Java Repos).")
    intervention: str = Field(description="The methodology, tool, toolchain, or process being evaluated.")
    comparison: Optional[str] = Field(None, description="What the intervention is compared against (e.g., Manual testing, Baseline Model X, None).")
    outcome: str = Field(description="The measurement variables tracked (e.g., Execution speed, Code coverage, Precision score).")
    context: str = Field(description="The environment details (e.g., Enterprise cloud settings, Academic lab, Constraints).")

class EvidenceClaim(BaseModel):
    """The specific empirical findings generated by the paper."""
    claim_summary: str = Field(description="The literal finding or result (e.g., 'Intervention X improved performance by 12% over Baseline Y').")
    direction: str = Field(description="The outcome direction. Must be one of: 'Positive', 'Negative', 'Neutral', 'Mixed'. Key for contradiction detection.")
    supporting_metrics: list[str] = Field(default_factory=list, description="Raw data points, p-values, or values supporting this specific claim.")
    contradicts_external_literature: Optional[str] = Field(None, description="Does the author explicitly mention their result conflicts with prior work? If so, capture who/what.")

class PaperProfile(BaseModel):
    """The master profile for a single study in your review matrix."""
    paper_id: str = Field(description="A unique identifier, usually Citation Key (e.g., 'Smith2024').")
    title: str = Field(description="Full paper title.")
    publication_year: int = Field(description="Crucial for trend analysis over a timeline.")
    
    # Scope and Framework
    scope_picoc: PICOC = Field(description="The PICOC parameters for this study.")
    
    # Findings & Future-proofing
    empirical_claims: list[EvidenceClaim] = Field(default_factory=list, description="List of discrete claims extracted from the results section.")
    author_stated_gaps: list[str] = Field(default_factory=list, description="Explicit future work, limitations, or unaddressed gaps mentioned by the author.")



# State definitions TODO: move pydantic models to the suitable section above. 


GeneralResearchDomain = Literal[
    "technology_and_computer_science",  # Software, AI, cybersecurity, robotics
    "healthcare_and_medicine",          # Clinical trials, public health, nursing
    "social_sciences",                  # Psychology, education, sociology, policy
    "business_and_management",          # Economics, supply chain, HR, marketing
    "natural_and_physical_sciences",    # Physics, chemistry, environmental science
    "humanities_and_arts"               # History, literature, philosophy, design
]

class PICOCQuestion(TypedDict):
    population: list[str]
    intervention: list[str]
    comparison: list[str]
    outcome: list[str]
    context: list[str]


class FormulatedQuestion(TypedDict):
    domain: GeneralResearchDomain
    review_type: Literal['systematic', 'narrative', 'scoping', 'rapid', 'umbrella']
    framework: Literal['PICO', 'PICOC', 'PCC']
    question: PICOCQuestion


class BaseState(TypedDict):
    messages: Annotated[list[AnyMessage], operator.add]
    llm_call: int
    formulated_question: FormulatedQuestion


# TODO: this is an internal state and should be moved to question formulation code.
class QuestionFormulationState(BaseState, total=False):
    user_clarification_count: int
    needs_clarification: bool
    clarification_question: str
    formulated_question: FormulatedQuestion


# Query expansion states
class Concept(BaseModel):
    name: str = Field(description="Name of the dimension, like population, context, comparison, etc, in PICOC framework.")
    value: list[str] = Field(description="The value of the dimension as mentioned in the Formulated Question.")
    synonyms: list[str] = Field(description="Synonyms for the dimension concept as used in the popular literature.")


class Query(BaseModel):
    database: Literal["arXiv", "openalex", "semantic_scholar"]
    search_strings: list[str] = Field(description="Final searchable string formatted as per the database type.")


class ExpandedQuery(BaseModel):
    framework: Literal['PICO', 'PICOC', 'PCC'] = Field(description="Name of the framework chosen to formulate the research question.")
    concepts: list[Concept]
    queries: list[Query]

class QueryExpansionState(BaseState):
    formulated_question: FormulatedQuestion
    expanded_queries: ExpandedQuery



class RetrieverState(QueryExpansionState):
    retrievals: ListRetrievals = []
    filtered_retrievals: ListRetrievals
    deduplicated_retrievals: ListRetrievals

class EvidenceSynthesisState(RetrieverState):
    paper_profiles: list[PaperProfile]